services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3306:3306' # DEV
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - '3000:3000' # DEV
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

volumes:
  db_data: